Repository atlp-rwanda/e-commerce-bitcrafters-bn, pull requests merged in 2024-04, with the labels that each got.

#16 #187364718 Run codeclimate & test coverage after test run with CI
  .circleci/config.yml
  .codeclimate.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/dummy.ts
  test/dummy.test.ts
Labels: Ready to be merged

#25 Fix - Rebasing develop
  .circleci/config.yml
  .codeclimate.yml
  .github/pull_request_template.md
  .gitignore
  README.md
  index.ts
  package-lock.json
  package.json
  src/dummy.ts
  test/dummy.test.ts
Labels: Ready for peer review, Changes requested

#33 [#187364721] Setup API Documentation using Swagger
  index.ts
  package-lock.json
  package.json
  src/helpers/swagger.ts
  src/routes/swagger.ts
Labels: Ready for peer review

#35 [#187364715] Setup ESLint and Pre-commit to run tests and ESLint format
  .circleci/config.yml
  .codeclimate.yml
  .eslintignore
  .eslintrc.json
  .husky/pre-commit
  .prettierignore
  .prettierrc
  .sequelizerc.ts
  README.md
  index.ts
  package-lock.json
  package.json
  src/config/database.ts
  src/dummy.ts
  src/helpers/swagger.ts
  src/migrations/20240407175814-create-user.js
  src/models/user.ts
  src/routes/swagger.ts
  test/dummy.test.ts
  tsconfig.json
Labels: Ready to be merged

#27 [#187364719] GitHub actions with readme badge
  .github/workflows/ci.yml
  .nycrc.json
  .sequelizerc.ts
  package-lock.json
  package.json
  src/migrations/20240407175814-create-user.js
Labels: Ready for peer review

#26 #187364716 Integrate HoundCI with badge attached to readme
  .hound.yaml
  README.md
  package-lock.json
Labels: Ready to be merged

#42 [#187364726] -On successful registration, users should receive a JWT
  .github/workflows/ci.yml
  .hound.yaml
  .nycrc.json
  .sequelizerc
  docker-compose.yaml
  index.ts
  package-lock.json
  package.json
  src/controllers/UserController.ts
  src/database/config/config.js
  src/database/config/config.ts
  src/database/config/db.config.ts
  src/database/migrations/20240425073125-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/models/userModel.ts
  src/docs/signupDocs.ts
  src/helpers/swagger.ts
  src/routes/userRoute.ts
  src/validations/userValidation.ts
  test/signup.test.ts
  tsconfig.json
Labels: Ready for peer review

#41 [#187364729] User Login
  index.ts
  package-lock.json
  package.json
  src/controllers/LoginController.ts
  src/database/config/config.js
  src/database/migrations/20240427140502-create-user.js
  src/database/seeders/20240423192321-demo-user.js
  src/docs/loginDocs.ts
  src/docs/signupDocs.ts
  src/helpers/swagger.ts
  src/routes/loginRoute.ts
  src/validations/userLogin.ts
  test/login.test.ts
  test/signup.test.ts
Labels: Ready for peer review
