Repository atlp-rwanda/e-commerce-bitcrafters-bn, pull requests merged in 2024-05, with the labels that each got.

#55 Fixing: Adding a trailing slash for PRs to access individual PRs link on render
  src/helpers/swagger.ts
Labels: Ready to be merged

#53 #187364726 -Fixing user registration validation and removing token while user signed up
  .nycrc.json
  package.json
  src/config/index.ts
  src/controllers/LoginController.ts
  src/controllers/UserController.ts
  src/helpers/swagger.ts
  src/routes/swagger.ts
  src/routes/userRoute.ts
  src/utils/jwt.ts
  src/utils/validateRequest.ts
  test/jwtConfiguration.test.ts
  test/signup.test.ts
Labels: Ready for peer review

#57 Fix: Removing ESLint errors
  .eslintrc.json
  src/helpers/swagger.ts
  src/routes/userRoute.ts
  src/utils/jwt.ts
  test/signup.test.ts
Labels: Ready to be merged

#56 Fix: Adding global middlewares, services and utils
  .gitignore
  index.ts
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/LoginController.ts
  src/database/models/userModel.ts
  src/middlewares/authenticationMiddleware.ts
  src/middlewares/index.ts
  src/services/userServices.ts
  src/utils/jwt.ts
  src/utils/passwords.ts
  src/utils/sendEmail.ts
  src/utils/swagger.ts
  test/jwt.test.ts
  test/jwtConfiguration.test.ts
  test/middlewares.spec.ts
  test/passwords.test.ts
  test/sendEmail.test.ts
  test/userServices.test.ts
Labels: Ready to be merged

#58 Fix: Solving ESLint Error
  .eslintrc.json
Labels: Ready to be merged

#49 #[187364737] - An admin should be able to set roles and permissions
  package-lock.json
  package.json
  src/controllers/UserController.ts
  src/database/models/userModel.ts
  src/docs/userDocs.ts
  src/middlewares/authenticationMiddleware.ts
  src/routes/userRoute.ts
  test/changeUserRole.test.ts
Labels: Ready to be merged

#48 #[187364735] users profiles endpoints
  .env.example
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/controllers/LoginController.ts
  src/controllers/UserController.ts
  src/database/migrations/20240504073916-userProfile.js
  src/database/models/userModel.ts
  src/database/models/userProfile.ts
  src/docs/userProfileDocs.ts
  src/middlewares/fileUpload.ts
  src/routes/userRoute.ts
  src/services/userServices.ts
  src/utils/cloudinary.ts
  src/validations/userValidation.ts
  test/userProfile.test.ts
  test/userServices.test.ts
Labels: Ready to be merged

#46 [#187364733] -Ft two factor authentication for sellers
  .codeclimate.yml
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/LoginController.ts
  src/controllers/UserController.ts
  src/database/models/userModel.ts
  src/docs/signupDocs.ts
  src/routes/loginRoute.ts
  src/routes/userRoute.ts
  src/utils/otpEmailTemplate.ts
  src/utils/redisConfiguration.ts
  src/utils/sendEmail.ts
  src/utils/swagger.ts
  src/validations/userValidation.ts
  test/login.test.ts
  test/signup.test.ts
  test/verifyOtp.test.ts
Labels: Ready to be merged

#43 [#187364730]User can login to the app via google
  .github/workflows/ci.yml
  index.ts
  package-lock.json
  package.json
  src/config/index.ts
  src/config/passport.ts
  src/controllers/LoginController.ts
  src/database/migrations/20240515174453-passwordShouldBeNull.js
  src/database/models/userModel.ts
  src/docs/googleAuthDocs.ts
  src/dummy.ts
  src/routes/loginRoute.ts
  src/types.d.ts
  test/dummy.test.ts
  test/googleAuth.test.ts
  test/login.test.ts
  test/passport.test.ts
Labels: Ready to be merged

#69 Fixing Pre-commit to remove tests
  .husky/pre-commit
  package.json
Labels: Ready to be merged

#45 #[187364724] - A successfully registered user should receive an email to verify their account email
  .codeclimate.yml
  .env.example
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/controllers/LoginController.ts
  src/controllers/UserController.ts
  src/database/migrations/20240429100222-create-token.js
  src/database/migrations/20240501064534-add_verified_column.js
  src/database/models/tokenModel.ts
  src/docs/signupDocs.ts
  src/middlewares/authenticationMiddleware.ts
  src/routes/userRoute.ts
  src/services/tokenServices.ts
  src/utils/emailTemplates/index.ts
  src/validations/paramValidation.ts
  src/validations/userValidation.ts
  test/emailTemplates.test.ts
  test/login.test.ts
  test/loginController.test.ts
  test/middlewares.spec.ts
  test/signup.test.ts
  test/userServices.test.ts
  test/verifyEmail.test.ts
Labels: Ready to be merged, Need Rebase

#47 [#187364738] - A seller should be able to add/create a product
  .gitignore
  index.ts
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/productController.ts
  src/database/migrations/20240502221817-create-collection-model.js
  src/database/migrations/20240502222701-create-product-model.js
  src/database/models/collectionModel.ts
  src/database/models/productModel.ts
  src/database/seeders/20240506020152-demo-collection.js
  src/docs/collectionDocs.ts
  src/docs/productDocs.ts
  src/middlewares/multer.ts
  src/routes/productRoute.ts
  src/validations/collectionValidation.ts
  src/validations/productValidation.ts
  test/collection.test.ts
  test/product.test.ts
Labels: Ready to be merged

#38 [#187364728] Logout Functionality
  package-lock.json
  package.json
  src/controllers/LoginController.ts
  src/docs/googleAuthDocs.ts
  src/docs/loginDocs.ts
  src/docs/logoutDocs.ts
  src/docs/signupDocs.ts
  src/middlewares/authenticationMiddleware.ts
  src/routes/userRoute.ts
  test/changeUserRole.test.ts
  test/login.test.ts
Labels: Ready to be merged

#70 Fixing uploads directory
  .gitignore
  uploads/.gitkeep
Labels: Ready to be merged

#63 [#187364739] Sellers manually mark products as available or unavailable
  package-lock.json
  package.json
  src/controllers/productController.ts
  src/database/migrations/20240519183612-Products.js
  src/database/models/productModel.ts
  src/database/seeders/20240506020152-demo-collection.js
  src/database/seeders/20240517065459-demo-Product.js
  src/docs/ProductStatusDocs.ts
  src/routes/productRoute.ts
  src/services/productServices.ts
  src/services/userServices.ts
  src/types.d.ts
  src/utils/cloudinary.ts
  src/utils/redisConfiguration.ts
  src/validations/productValidation.ts
  test/productStatus.test.ts
  test/userProfile.test.ts
Labels: Ready to be merged

#51 #[187364740] A seller should be able to delete a specific item from their collection
  src/controllers/productController.ts
  src/docs/productDocs.ts
  src/routes/productRoute.ts
  src/services/productServices.ts
  src/validations/paramValidation.ts
  test/deleteProduct.test.ts
  test/productServices.test.ts
Labels: Ready to be merged

#44 [#187364732] Reset Password via email
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/UserController.ts
  src/database/models/userModel.ts
  src/docs/userDocs.ts
  src/routes/userRoute.ts
  src/services/tokenServices.ts
  src/utils/jwt.ts
  src/validations/userValidation.ts
  test/resetPassword.test.ts
Labels: Ready to be merged

#50 [#187364741] A User should be able to view a specific item
  package-lock.json
  package.json
  src/controllers/productController.ts
  src/docs/viewItemDocs.ts
  src/routes/productRoute.ts
  test/findProduct.test.ts
Labels: Ready for peer review

#62 Fix eslint errors test coverage
  .eslintrc.json
  src/database/models/userModel.ts
  src/database/models/userProfile.ts
  src/middlewares/fileUpload.ts
  src/utils/cloudinary.ts
  test/userProfile.test.ts
Labels: Ready to be merged

#64 Fix: (googleAuth) id error
  src/controllers/LoginController.ts
  src/docs/googleAuthDocs.ts
Labels: Ready to be merged

#52 [#187364736] Admin can disable account for various reasons
  src/controllers/LoginController.ts
  src/controllers/adminController.ts
  src/database/migrations/20240504091720-AddStatusColum.js
  src/database/models/userModel.ts
  src/docs/changeStatusDocs.ts
  src/docs/userDocs.ts
  src/middlewares/authenticationMiddleware.ts
  src/routes/userRoute.ts
  src/utils/emailTemplates/disableUserTemplate.ts
  src/utils/emailTemplates/enableUserTemplate.ts
  test/changeStatus.test.ts
  test/enableUserTemplate.test.ts
Labels: Ready to be merged

#65 [#187364742] - Feature(Product Listing): A User Should be able to list all Items
  .codeclimate.yml
  package-lock.json
  package.json
  src/controllers/productController.ts
  src/docs/productDocs.ts
  src/middlewares/authenticationMiddleware.ts
  src/routes/productRoute.ts
  src/services/productServices.ts
  test/product.test.ts
Labels: Ready to be merged

#78 Fix(View Collections): Added viewing collections
  src/controllers/productController.ts
  src/docs/collectionDocs.ts
  src/docs/productDocs.ts
  src/routes/productRoute.ts
  src/services/productServices.ts
  test/product.test.ts
Labels: Ready for peer review, improvement

#73 [#187364744] Feature: Adding product to a wishlist
  index.ts
  src/controllers/wishlistController.ts
  src/database/migrations/20240522225737-create-wishlist.js
  src/database/models/userModel.ts
  src/database/models/wishlistModel.ts
  src/docs/wishlistDocs.ts
  src/routes/wishlistRoute.ts
  test/wishlist.test.ts
Labels: Ready to be merged

#71 [#187364746] Buyer should add item to their cart
  index.ts
  src/controllers/cartController.ts
  src/database/migrations/20240520205533-create-cart.js
  src/database/models/cartModel.ts
  src/database/models/userModel.ts
  src/docs/cartDocs.ts
  src/routes/cartRoute.ts
  src/validations/cartValidation.ts
  test/addToCart.test.ts
Labels: Ready to be merged

#66 [#187364757] Ft-the notification should be sent to the the right user
  index.html
  index.ts
  package-lock.json
  package.json
  src/controllers/NotificationController.ts
  src/controllers/productController.ts
  src/database/migrations/20240521095936-create-notification.js
  src/database/models/notificationModel.ts
  src/docs/notificationDocs.ts
  src/middlewares/socketMiddleware.ts
  src/routes/notificationRoute.ts
  src/services/notificationServices.ts
  src/services/tokenServices.ts
  src/utils/socketEvents.ts
  test/collection.test.ts
  test/jwt.test.ts
  test/middlewares.spec.ts
  test/notification.test.ts
  test/notificationService.test.ts
  test/product.test.ts
  test/productServices.test.ts
  test/socketEvents.test.ts
Labels: Ready to be merged

#72 [#187364743] A seller can update product from their collection
  src/controllers/productController.ts
  src/docs/updateProduct.ts
  src/routes/productRoute.ts
  test/updateProduct.test.ts
Labels: Ready to be merged

#74 [#187364748] - Feature (View Cart): A buyer should be able to view their cart
  src/controllers/cartController.ts
  src/docs/cartDocs.ts
  src/routes/cartRoute.ts
  test/addToCart.test.ts
Labels: Ready to be merged

#86 Fixing adding product to cart feature
  src/controllers/cartController.ts
  test/addToCart.test.ts
Labels: Ready to be merged

#80 #[187364755] Expired Products should not appear on the list of the available products
  .env.example
  error.log
  index.ts
  info.log
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/productExpiryCronJob.ts
  src/database/migrations/20240527102821-add_expired_column.js
  src/database/models/productModel.ts
  src/utils/expiryProductEmailTemplate.ts
  src/utils/logger.ts
  src/utils/productExpiryNotify.ts
  test/productExpiry.test.ts
Labels: Ready to be merged

#88 fix(render): add catch method for redis
  .gitignore
  src/utils/redisConfiguration.ts
Labels: Ready for peer review

#89 fix(logs):remove log files
  error.log
  info.log
Labels: Ready to be merged

#84 [#187364753] Buyer should be able to checkout
  index.ts
  package-lock.json
  package.json
  src/controllers/checkoutController.ts
  src/database/migrations/20240530061851-create-order.js
  src/database/models/orderModel.ts
  src/docs/checkoutDocs.ts
  src/middlewares/checkCartMiddleware.ts
  src/routes/checkoutRoute.ts
  src/services/notificationServices.ts
  src/utils/socketEvents.ts
  src/validations/orderValidation.ts
  test/checkoutController.test.ts
  test/middlewares.spec.ts
  test/notificationService.test.ts
Labels: Ready to be merged

#83 [#187364749] - Feature(Clear cart): User can clear their cart
  src/controllers/cartController.ts
  src/docs/cartDocs.ts
  src/routes/cartRoute.ts
  src/services/cartService.ts
  test/addToCart.test.ts
  test/cartServices.test.ts
Labels: Ready to be merged, Changes requested

#85 [#187364754] A user should be able to mark one/all Notification as read
  package-lock.json
  package.json
  src/controllers/NotificationController.ts
  src/database/models/notificationModel.ts
  src/docs/notificationDocs.ts
  src/docs/updateNotificationStatus.ts
  src/routes/notificationRoute.ts
  test/notificationStatus.test.ts
Labels: Ready to be merged

#90 Fix: Rename index.html to public/index.html
  error.log
  index.ts
  info.log
  public/index.html
Labels: Ready to be merged

#77 [#187364750] A user should be able to search a product
  .gitignore
  error.log
  info.log
  src/controllers/searchProduct.ts
  src/database/migrations/20240530223921-add-tsv-column.js
  src/database/models/productModel.ts
  src/docs/searchProductDocs.ts
  src/routes/productRoute.ts
  src/services/productServices.ts
  test/productServices.test.ts
  test/searchProduct.test.ts
Labels: Ready to be merged

#91 fix(checkout):clear cart after ordering
  src/controllers/checkoutController.ts
  src/middlewares/checkCartMiddleware.ts
Labels: Ready to be merged
