Repository atlp-rwanda/e-commerce-bitcrafters-bn, pull requests merged in 2024-06, with the labels that each got.

#82 [#187364747] Buyer should be able to update their cart
  src/controllers/cartController.ts
  src/docs/deleteProductFromCartDocs.ts
  src/docs/updateCartDocs.ts
  src/routes/cartRoute.ts
  test/deleteProducFromCart.test.ts
  test/updateCart.test.ts
Labels: Ready to be merged

#75 #[187364745] A buyer should be able to provide a review on a product
  package-lock.json
  src/controllers/reviewsController.ts
  src/database/migrations/20240519145251-productReviews.js
  src/database/models/reviewsModel.ts
  src/database/models/userModel.ts
  src/docs/productReviewsDocs.ts
  src/middlewares/productMiddleware.ts
  src/routes/productRoute.ts
  src/validations/productValidation.ts
  test/productMiddleware.test.ts
  test/productReviews.test.ts
Labels: Ready to be merged

#95 fix(order): modify order statuses
  src/database/migrations/20240604112117-modify-statusColumn.js
  src/database/models/orderModel.ts
  src/middlewares/productMiddleware.ts
  test/productMiddleware.test.ts
Labels: Ready to be merged

#87 [#187364751] Buyer should be able to track their order status
  index.ts
  src/controllers/orderController.ts
  src/docs/orderStatusDocs.ts
  src/routes/orderRoute.ts
  src/services/notificationServices.ts
  src/services/orderService.ts
  src/utils/socketEvents.ts
  src/validations/orderValidation.ts
  test/orderStatus.test.ts
Labels: Ready to be merged

#96 [#187364758] Ft users should be able to chat on the app
  index.ts
  package-lock.json
  package.json
  public/chart.html
  src/controllers/LoginController.ts
  src/controllers/adminController.ts
  src/controllers/chatController.ts
  src/database/migrations/20240605084412-create-chat.js
  src/database/models/chatModel.ts
  src/routes/chatRoute.ts
  src/utils/chatNamespace.ts
  src/utils/customSocketTypes.ts
  test/chatController.test.ts
  test/chatNamespace.test.ts
  test/chatRoute.test.ts
  test/login.test.ts
  test/signup.test.ts
  test/updateCart.test.ts
  test/verifyEmail.test.ts
Labels: Ready for peer review, Ready to be merged

#92 [#187364756] User should be prompted to update password in x amount of time
  .github/workflows/ci.yml
  index.ts
  src/config/index.ts
  src/controllers/LoginController.ts
  src/controllers/UserController.ts
  src/controllers/productExpiryCronJob.ts
  src/database/migrations/20240606172802-newAttributes.js
  src/database/models/userModel.ts
  src/routes/userRoute.ts
  src/utils/emailTemplates/passwordExpiryTemplate.ts
  src/utils/passwordUpdateEvent.ts
  test/passwordExpiryTemplate.test.ts
  test/passwordUpdateEvents.test.ts
  test/resetPassword.test.ts
Labels: Ready to be merged

#99 Fixx: Tests & product image update
  src/docs/updateProduct.ts
  src/routes/productRoute.ts
  test/changeStatus.test.ts
  test/login.test.ts
  test/signup.test.ts
  test/verifyOtp.test.ts
Labels: Ready to be merged

#94 [#187364741] Fix-User should be able to view specific item with review information
  index.ts
  src/controllers/productController.ts
  src/database/models/productModel.ts
  src/database/models/reviewsModel.ts
  test/findProduct.test.ts
Labels: Ready for peer review

#93 [#187364664] - Feature(MoMo API): Integrating Mobile money in our payment mechanism
  index.ts
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/checkoutController.ts
  src/controllers/momoPayment.ts
  src/database/migrations/20240602120733-add_reference_column.js
  src/database/models/orderModel.ts
  src/docs/paymentDocs.ts
  src/middlewares/momoAuth.ts
  src/routes/MoMoRoute.ts
  src/services/productServices.ts
  src/validations/orderValidation.ts
  test/login.test.ts
  test/logout.test.ts
  test/payment.test.ts
  test/updateCart.test.ts
  test/verifyEmail.test.ts
Labels: Ready for peer review

#79 [#187364752] Feature: Make Payment using Stripe API
  .github/workflows/ci.yml
  index.ts
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/checkoutController.ts
  src/controllers/paymentStripeController.ts
  src/database/migrations/20240602101557-AddOrderNumberAndExpectedDeliveryDateToOrders.js
  src/docs/paymentStripeDocs.ts
  src/routes/paymentStripeRoute.ts
  src/routes/stripeRoute.ts
  src/services/orderService.ts
  src/utils/logger.ts
  test/paymentStripe.test.ts
Labels: Ready to be merged

#100 [#187764396] fix error from the db are shown to the end user
  src/controllers/LoginController.ts
  src/controllers/cartController.ts
  src/controllers/paymentStripeController.ts
  src/controllers/productController.ts
  src/controllers/searchController.ts
  src/controllers/wishlistController.ts
  src/routes/productRoute.ts
  test/searchProduct.test.ts
Labels: Ready for peer review

#101 Fixing: Add space for node
  package.json
Labels: Ready to be merged

#103 fix :redis reconfiguration
  .github/workflows/ci.yml
  src/utils/redisConfiguration.ts
Labels: Ready to be merged

#108 fix:handle redis errors
  src/utils/redisConfiguration.ts
Labels: Ready to be merged

#107 Fix: Adding pagination and correcting all user retrieval
  src/controllers/NotificationController.ts
  src/controllers/adminController.ts
  src/controllers/productController.ts
  src/controllers/wishlistController.ts
  src/docs/changeStatusDocs.ts
  src/docs/notificationDocs.ts
  src/docs/wishlistDocs.ts
  src/services/notificationServices.ts
  src/services/userServices.ts
  src/utils/paginator.ts
  test/changeStatus.test.ts
  test/notification.test.ts
  test/wishlist.test.ts
Labels: Ready to be merged

#109 Fix 3D secure payment
  src/controllers/paymentStripeController.ts
  test/paymentStripe.test.ts
Labels: Ready to be merged

#106 Fix Google authentication & Notification
  .github/workflows/ci.yml
  src/config/index.ts
  src/controllers/LoginController.ts
  src/controllers/NotificationController.ts
  src/controllers/productController.ts
  src/docs/notificationDocs.ts
  src/docs/updateProduct.ts
  src/routes/notificationRoute.ts
  src/routes/productRoute.ts
  test/googleAuth.test.ts
  test/notificationStatus.test.ts
  test/updateProduct.test.ts
Labels: Ready to be merged

#102 [#187764392]fix(product Orders): implement endpoint for admin able to get all orders
  src/controllers/orderController.ts
  src/docs/orderStatusDocs.ts
  src/routes/orderRoute.ts
  test/orderStatus.test.ts
Labels: Ready to be merged

#105 Fix logout functionality
  src/controllers/LoginController.ts
  src/middlewares/authenticationMiddleware.ts
  test/loginController.test.ts
  test/middlewares.spec.ts
Labels: Ready to be merged

#110 fix: reset password link
  src/config/index.ts
  src/controllers/UserController.ts
Labels: Ready to be merged

#112 Fix: redirection on login of frontend
  src/controllers/LoginController.ts
  test/googleAuth.test.ts
Labels: Ready to be merged

#113 Fix: Fixing cannot set to headers error of googleAuthentication
  src/controllers/LoginController.ts
  test/googleAuth.test.ts
Labels: Ready to be merged
